version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ai-task-manager-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai-task-manager
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
